#!/bin/bash

echo "Starting main script..."

./script/ask_details.sh


setup_firewall.sh
setup_fail2ban.sh
setup_timezone.sh
disable_swap.sh
enable_swap.sh
tune_sysctl.sh
sysctl_info.sh
harden_shm.sh
check_shm.sh
disable_ipv6.sh
sysctl_tuning.sh
check_tcp_congestion.sh
fstab_noatime.sh
set_ulimit.sh
enable_pam_limits.sh
install_nginx.sh
install_mariadb_php.sh
nginx_base_config.sh
nginx_basic_settings.sh
nginx_buffers.sh
nginx_timeouts.sh
nginx_gzip.sh
nginx_brotli.sh
nginx_file_handle_cache.sh
nginx_http_block.sh
set_aliases.sh
secure_mariadb.sh
mariadb_perf_schema.sh
setup_mariadb.sh
setup_mysql_tuner.sh
harden_php.sh
php_fpm_hardening.sh
nginx_vhost_example.sh
nginx_browser_caching.sh
nginx_fastcgi_optimize.sh
nginx_vhost_example_full.sh
setup_example_db.sh
wordpress_setup_example.sh
wp_setup_cli_example.sh
php_fpm_pool_example.sh
php_fpm_harden_example.sh
set_permissions_example.sh
php_fpm_tmp_wp_cleanup.sh
setup_ssl_example.sh
nginx_ssl_setup_example.sh
nginx_https_example.sh
ssl_verification_renewal_example.sh
nginx_headers_caching_example.sh
nginx_security_example.sh
nginx_example_security_setup.sh
nginx_example_rate_limit.sh
wordpress_db_privilege_restrict.sh
pagespeed_check.sh
wordpress_disable_post_revisions.sh
wordpress_set_memory_limit.sh
wordpress_disable_wp_cron.sh
php_opcache_setup.sh
nginx_fastcgi_cache_setup.sh
nginx_fastcgi_cache_remove.sh
create_wp_super_cache_excludes.sh
wp_super_cache_temp_setup.sh

